### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by LuminousLoreBloom** [uMatrix-Rules/uMatrix-Rules-Domain#4]
```reddit.com redditstatic.com script allow``` - Required to reply to comments (and probably more).
```reddit.com redditmedia.com frame allow```
```reddit.com redditmedia.com xhr allow```
```reddit.com g.redditmedia.com plugin allow```

uMatrix version - 1.0.0
Chrome version - 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)

**Comment by Riajyuu** [comment]
Thx for getting this.
Unfortunately I deleted my accounts some days ago and I'm not gonna register another.
If trust me enough, give me an account [here](https://t.me/Engorgio) and I'd investigate more.

**Comment by Riajyuu** [comment]
@Mystiflow Just a little question here:

```reddit.com redditmedia.com frame allow```
```reddit.com redditmedia.com xhr allow```
```reddit.com g.redditmedia.com plugin allow```

But check out [here](https://rictusempra.github.io/uMatrix-Rules/) at `Shubbanuffa`
