### ISSUE TITLE
Rules Level

### ISSUE THREAD

**Issue by Riajyuu** [uMatrix-Rules/uMatrix-Rules-Domain#6]
In the latest uMatrix release, you are allowed to adjust scope level from `domain` to `site` or `global`.
I don't think `global` level really makes sense and this repository is now `domain` level.

So questions can be concluded as:

1. whether we create rules for per-site-level scopes?
    - review & rework to existed rules
    - update docs

1. how should we distribute it?

**Comment by elypter** [comment]
there are some useful applications for global like video embed frames and other things that you want to have working on every site or on none.

in most cases domain scope is the best choice but it might be worth to have different rules for subdomains if those are different sites like maps.google.com and groups.google.com but that has to be decided for each new rule.

btw do you know if umatrix understands something like google.* or maps.google.* so you dont have to make rules for each tld?

this should continue to be distributed in a single list. a reason to create multiple lists would only be to have a list that only just allowes enough to browse a site and another on where all account features work too as that typically involves enabling cookies and other nasty stuff.
